name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          cd services/model_training
          pip install -r requirements.txt

      - name: Run model training
        run: |
          cd services/model_training
          python app.py

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          cd services/model_training
          docker build -t ai_management_system:latest .

      - name: Push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag ai_management_system:latest your_dockerhub_username/ai_management_system:latest
          docker push your_dockerhub_username/ai_management_system:latest

      - name: Deploy application
        run: |
          # Add your deployment commands here
          echo "Deploying application..."